server:
  port: 8082 
  
spring:
  application:
    name: gateway
 
eureka:
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:9090/eureka
     instance:
       hostName: localhost
    
       
 