
server:
  port: 8081 
  
spring:
  application:
    name: SECOND-APP
 
eureka:
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:9090/eureka
     instance:
       hostName: localhost